import { IsDate, IsInt, IsString, Validate, IsNotEmpty } from "class-validator";
import 'reflect-metadata';

export class Patients {

    //   id is autogenerated in db so no need for validation
    // id:number;

    @IsNotEmpty()
    @IsString({ message: 'name should not be empty' })
    name: string;

    @IsNotEmpty()
    @IsInt()
    grafts: number;

    @IsNotEmpty()
    @IsInt()
    price: number;

    // @IsNotEmpty({
    //     message: 'Name for role is required',
    // })
    // public roles: Array<{ name: string, privileges: number[] }>;

}